package scanner

// ================================================================
// 二十八、AI Agent / AI 开发工具
// ================================================================
func toolsCatAI() []Tool {
	return []Tool{
		{Name: "Cursor",
			WinPaths:   []string{"${APPDATA}\\Cursor", "${APPDATA}\\Code\\User\\globalStorage\\cursor-dev"},
			MacPaths:   []string{"~/Library/Application Support/Cursor"},
			LinuxPaths: []string{"${CONFIG}/Cursor"},
			Extensions: []string{".json", ".yaml", ".yml", ".md"}, MaxFileSize: mb(5)},
		{Name: "Windsurf",
			WinPaths:   []string{"${APPDATA}\\Windsurf"},
			MacPaths:   []string{"~/Library/Application Support/Windsurf"},
			LinuxPaths: []string{"${CONFIG}/Windsurf"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "Claude_Desktop",
			WinPaths:   []string{"${APPDATA}\\Claude", "${LOCALAPPDATA}\\Claude"},
			MacPaths:   []string{"~/Library/Application Support/Claude"},
			LinuxPaths: []string{"${CONFIG}/claude"},
			Extensions: []string{".json", ".db", ".log", ".yaml", ".yml"}, MaxFileSize: mb(10)},
		{Name: "Claude_Code_CLI",
			WinPaths:   []string{"${HOME}\\.claude"},
			MacPaths:   []string{"~/.claude"},
			LinuxPaths: []string{"~/.claude"},
			Extensions: []string{".json", ".yaml", ".yml", ".md"}, MaxFileSize: mb(5)},
		{Name: "Continue_AI",
			WinPaths:   []string{"${APPDATA}\\Code\\User\\globalStorage\\continue.continue", "${HOME}\\.continue"},
			MacPaths:   []string{"~/.continue"},
			LinuxPaths: []string{"~/.continue"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "Cline",
			WinPaths:   []string{"${APPDATA}\\Code\\User\\globalStorage\\saoudrizwan.claude-dev"},
			MacPaths:   []string{"~/.vscode/extensions/saoudrizwan.claude-dev"},
			LinuxPaths: []string{"~/.vscode/extensions/saoudrizwan.claude-dev"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "Roo_Code",
			WinPaths:   []string{"${APPDATA}\\Code\\User\\globalStorage\\rooveterinaryinc.roo-cline"},
			MacPaths:   []string{"~/.vscode/extensions/rooveterinaryinc.roo-cline"},
			LinuxPaths: []string{"~/.vscode/extensions/rooveterinaryinc.roo-cline"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "Aider",
			WinPaths:   []string{"${HOME}\\.aider"},
			MacPaths:   []string{"~/.aider"},
			LinuxPaths: []string{"~/.aider"},
			Extensions: []string{".yml", ".yaml", ".conf", ".md", ".env"}, MaxFileSize: mb(2)},
		{Name: "Ollama",
			WinPaths:   []string{"${LOCALAPPDATA}\\ollama"},
			MacPaths:   []string{"~/.ollama"},
			LinuxPaths: []string{"~/.ollama"},
			Extensions: []string{".json"}, MaxFileSize: mb(2)},
		{Name: "LM_Studio",
			WinPaths:   []string{"${LOCALAPPDATA}\\LM Studio"},
			MacPaths:   []string{"~/.lm-studio"},
			LinuxPaths: []string{"${CONFIG}/lm-studio"},
			Extensions: []string{".json"}, MaxFileSize: mb(5)},
		{Name: "GitHub_Copilot",
			WinPaths:   []string{"${APPDATA}\\Code\\User\\globalStorage\\github.copilot"},
			MacPaths:   []string{"~/.vscode/extensions/github.copilot"},
			LinuxPaths: []string{"~/.vscode/extensions/github.copilot"},
			Extensions: []string{".json"}, MaxFileSize: mb(5)},
		{Name: "Amazon_Q_Developer",
			WinPaths:   []string{"${APPDATA}\\Code\\User\\globalStorage\\amazonwebservices.amazon-q-vscode"},
			MacPaths:   []string{"~/.vscode/extensions/amazonwebservices.amazon-q-vscode"},
			LinuxPaths: []string{"~/.vscode/extensions/amazonwebservices.amazon-q-vscode"},
			Extensions: []string{".json"}, MaxFileSize: mb(5)},
		{Name: "Codeium",
			WinPaths:   []string{"${APPDATA}\\Code\\User\\globalStorage\\codeium.codeium"},
			MacPaths:   []string{"~/.vscode/extensions/codeium.codeium"},
			LinuxPaths: []string{"~/.vscode/extensions/codeium.codeium"},
			Extensions: []string{".json"}, MaxFileSize: mb(5)},
		{Name: "Tabnine",
			WinPaths:   []string{"${LOCALAPPDATA}\\Tabnine"},
			MacPaths:   []string{"~/Library/Application Support/Tabnine"},
			LinuxPaths: []string{"${CONFIG}/Tabnine"},
			Extensions: []string{".json", ".config"}, MaxFileSize: mb(5)},
		{Name: "Supermaven",
			WinPaths:   []string{"${APPDATA}\\Code\\User\\globalStorage\\supermaven.supermaven"},
			MacPaths:   []string{"~/.vscode/extensions/supermaven.supermaven"},
			LinuxPaths: []string{"~/.vscode/extensions/supermaven.supermaven"},
			Extensions: []string{".json"}, MaxFileSize: mb(5)},
		{Name: "Cody_AI",
			WinPaths:   []string{"${APPDATA}\\Code\\User\\globalStorage\\sourcegraph.cody-ai"},
			MacPaths:   []string{"~/.vscode/extensions/sourcegraph.cody-ai"},
			LinuxPaths: []string{"~/.vscode/extensions/sourcegraph.cody-ai"},
			Extensions: []string{".json"}, MaxFileSize: mb(5)},
		{Name: "LiteLLM",
			WinPaths:   []string{"${HOME}\\.litellm"},
			MacPaths:   []string{"~/.litellm"},
			LinuxPaths: []string{"~/.litellm"},
			Extensions: []string{".json", ".yaml", ".yml", ".toml"}, MaxFileSize: mb(5)},
		{Name: "Open_Interpreter",
			WinPaths:   []string{"${HOME}\\.interpreter"},
			MacPaths:   []string{"~/.interpreter"},
			LinuxPaths: []string{"~/.interpreter"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "AutoGPT",
			WinPaths:   []string{"${HOME}\\.auto-gpt", "${HOME}\\.autogpt"},
			MacPaths:   []string{"~/.auto-gpt", "~/.autogpt"},
			LinuxPaths: []string{"~/.auto-gpt", "~/.autogpt"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "CrewAI",
			WinPaths:   []string{"${HOME}\\.crewai"},
			MacPaths:   []string{"~/.crewai"},
			LinuxPaths: []string{"~/.crewai"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "Dify",
			WinPaths:   []string{"${HOME}\\.dify"},
			MacPaths:   []string{"~/.dify"},
			LinuxPaths: []string{"~/.dify"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "Flowise",
			WinPaths:   []string{"${HOME}\\.flowise"},
			MacPaths:   []string{"~/.flowise"},
			LinuxPaths: []string{"~/.flowise"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "LangChain",
			WinPaths:   []string{"${HOME}\\.langchain", "${HOME}\\.lc"},
			MacPaths:   []string{"~/.langchain", "~/.lc"},
			LinuxPaths: []string{"~/.langchain", "~/.lc"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "LlamaIndex",
			WinPaths:   []string{"${HOME}\\.llamaindex"},
			MacPaths:   []string{"~/.llamaindex"},
			LinuxPaths: []string{"~/.llamaindex"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "MCP_Config",
			WinPaths:   []string{"${APPDATA}\\Code\\User\\globalStorage\\mcp", "${HOME}\\.mcp"},
			MacPaths:   []string{"~/.mcp"},
			LinuxPaths: []string{"~/.mcp"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "ChatGPT_Desktop",
			WinPaths:   []string{"${LOCALAPPDATA}\\OpenAI\\ChatGPT"},
			MacPaths:   []string{"~/Library/Application Support/com.openai.chat"},
			LinuxPaths: []string{},
			Extensions: []string{".json", ".db", ".log"}, MaxFileSize: mb(10)},
		{Name: "Perplexity_Desktop",
			WinPaths:   []string{"${LOCALAPPDATA}\\Perplexity"},
			MacPaths:   []string{"~/Library/Application Support/com.perplexity.desktop"},
			LinuxPaths: []string{},
			Extensions: []string{".json"}, MaxFileSize: mb(5)},
		{Name: "Zed_AI",
			WinPaths:   []string{"${APPDATA}\\Zed"},
			MacPaths:   []string{"~/.config/zed"},
			LinuxPaths: []string{"${CONFIG}/zed"},
			Extensions: []string{".json"}, MaxFileSize: mb(5)},
		{Name: "PearAI",
			WinPaths:   []string{"${APPDATA}\\PearAI"},
			MacPaths:   []string{"~/Library/Application Support/PearAI"},
			LinuxPaths: []string{"${CONFIG}/PearAI"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "Goose",
			WinPaths:   []string{"${HOME}\\.goose"},
			MacPaths:   []string{"~/.goose"},
			LinuxPaths: []string{"~/.goose"},
			Extensions: []string{".json", ".yaml", ".yml", ".toml"}, MaxFileSize: mb(5)},
		{Name: "Kodu",
			WinPaths:   []string{"${APPDATA}\\Kodu"},
			MacPaths:   []string{"~/Library/Application Support/Kodu"},
			LinuxPaths: []string{"${CONFIG}/Kodu"},
			Extensions: []string{".json"}, MaxFileSize: mb(5)},
		{Name: "Hugging_Face_CLI",
			WinPaths:   []string{"${HOME}\\.cache\\huggingface", "${HOME}\\.huggingface"},
			MacPaths:   []string{"~/.cache/huggingface", "~/.huggingface"},
			LinuxPaths: []string{"~/.cache/huggingface", "~/.huggingface"},
			Extensions: []string{".json", ".yaml", ".yml", ".toml"}, MaxFileSize: mb(5)},
		{Name: "Replicate_CLI",
			WinPaths:   []string{"${HOME}\\.replicate"},
			MacPaths:   []string{"~/.replicate"},
			LinuxPaths: []string{"~/.replicate"},
			Extensions: []string{".json", ".yaml", ".yml", ".toml"}, MaxFileSize: mb(5)},
		{Name: "Groq_CLI",
			WinPaths:   []string{"${HOME}\\.groq"},
			MacPaths:   []string{"~/.groq"},
			LinuxPaths: []string{"~/.groq"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "Together_AI_CLI",
			WinPaths:   []string{"${HOME}\\.together"},
			MacPaths:   []string{"~/.together"},
			LinuxPaths: []string{"~/.together"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "Fireworks_AI_CLI",
			WinPaths:   []string{"${HOME}\\.fireworks"},
			MacPaths:   []string{"~/.fireworks"},
			LinuxPaths: []string{"~/.fireworks"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "DeepSeek_CLI",
			WinPaths:   []string{"${HOME}\\.deepseek"},
			MacPaths:   []string{"~/.deepseek"},
			LinuxPaths: []string{"~/.deepseek"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "Mistral_AI_CLI",
			WinPaths:   []string{"${HOME}\\.mistral"},
			MacPaths:   []string{"~/.mistral"},
			LinuxPaths: []string{"~/.mistral"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "xAI_CLI",
			WinPaths:   []string{"${HOME}\\.xai", "${HOME}\\.grok"},
			MacPaths:   []string{"~/.xai", "~/.grok"},
			LinuxPaths: []string{"~/.xai", "~/.grok"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "ElevenLabs_CLI",
			WinPaths:   []string{"${HOME}\\.elevenlabs"},
			MacPaths:   []string{"~/.elevenlabs"},
			LinuxPaths: []string{"~/.elevenlabs"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "AssemblyAI_CLI",
			WinPaths:   []string{"${HOME}\\.assemblyai"},
			MacPaths:   []string{"~/.assemblyai"},
			LinuxPaths: []string{"~/.assemblyai"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "Deepgram_CLI",
			WinPaths:   []string{"${HOME}\\.deepgram"},
			MacPaths:   []string{"~/.deepgram"},
			LinuxPaths: []string{"~/.deepgram"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "Weights_Biases",
			WinPaths:   []string{"${HOME}\\.wandb"},
			MacPaths:   []string{"~/.wandb"},
			LinuxPaths: []string{"~/.wandb"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Neptune_AI",
			WinPaths:   []string{"${HOME}\\.neptune"},
			MacPaths:   []string{"~/.neptune"},
			LinuxPaths: []string{"~/.neptune"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Comet_ML",
			WinPaths:   []string{"${HOME}\\.comet-ml"},
			MacPaths:   []string{"~/.comet-ml"},
			LinuxPaths: []string{"~/.comet-ml"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "MLflow",
			WinPaths:   []string{"${HOME}\\.mlflow"},
			MacPaths:   []string{"~/.mlflow"},
			LinuxPaths: []string{"~/.mlflow"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Prefect",
			WinPaths:   []string{"${HOME}\\.prefect"},
			MacPaths:   []string{"~/.prefect"},
			LinuxPaths: []string{"~/.prefect"},
			Extensions: []string{".json", ".yaml", ".yml", ".toml"}, MaxFileSize: mb(5)},
		{Name: "Airflow",
			WinPaths:   []string{"${HOME}\\airflow", "${APPDATA}\\Airflow"},
			MacPaths:   []string{"~/airflow"},
			LinuxPaths: []string{"~/airflow"},
			Extensions: []string{".cfg", ".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "Modal_CLI",
			WinPaths:   []string{"${HOME}\\.modal"},
			MacPaths:   []string{"~/.modal"},
			LinuxPaths: []string{"~/.modal"},
			Extensions: []string{".json", ".yaml", ".yml", ".toml"}, MaxFileSize: mb(5)},
		{Name: "BentoML",
			WinPaths:   []string{"${HOME}\\.bentoml"},
			MacPaths:   []string{"~/.bentoml"},
			LinuxPaths: []string{"~/.bentoml"},
			Extensions: []string{".json", ".yaml", ".yml", ".toml"}, MaxFileSize: mb(5)},
		{Name: "Stability_AI_CLI",
			WinPaths:   []string{"${HOME}\\.stability"},
			MacPaths:   []string{"~/.stability"},
			LinuxPaths: []string{"~/.stability"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "RunwayML_CLI",
			WinPaths:   []string{"${HOME}\\.runwayml"},
			MacPaths:   []string{"~/.runwayml"},
			LinuxPaths: []string{"~/.runwayml"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},

		// ================================================================
		// 二十九、AI IDE / AI 工具（补充）
		// ================================================================
		{Name: "Bito_AI",
			WinPaths:   []string{"${APPDATA}\\Bito"},
			MacPaths:   []string{"~/Library/Application Support/Bito"},
			LinuxPaths: []string{"${CONFIG}/Bito"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "AskCodi",
			WinPaths:   []string{"${APPDATA}\\AskCodi"},
			MacPaths:   []string{"~/Library/Application Support/AskCodi"},
			LinuxPaths: []string{"${CONFIG}/AskCodi"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "CodeGPT",
			WinPaths:   []string{"${APPDATA}\\CodeGPT"},
			MacPaths:   []string{"~/Library/Application Support/CodeGPT"},
			LinuxPaths: []string{"${CONFIG}/CodeGPT"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Gemini_Code_Assist",
			WinPaths:   []string{"${APPDATA}\\Google\\Cloud Code", "${APPDATA}\\Google\\Gemini"},
			MacPaths:   []string{"~/Library/Application Support/Google/Cloud Code", "~/Library/Application Support/Google/Gemini"},
			LinuxPaths: []string{"${CONFIG}/google/cloud-code", "${CONFIG}/google/gemini"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Blackbox_AI",
			WinPaths:   []string{"${APPDATA}\\Blackbox AI"},
			MacPaths:   []string{"~/Library/Application Support/Blackbox AI"},
			LinuxPaths: []string{"${CONFIG}/Blackbox AI"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Replit",
			WinPaths:   []string{"${HOME}\\.config\\replit", "${HOME}\\.replit"},
			MacPaths:   []string{"~/.config/replit", "~/.replit"},
			LinuxPaths: []string{"~/.config/replit", "~/.replit"},
			Extensions: []string{".json", ".yaml", ".yml", ".env", ".toml"}, MaxFileSize: mb(5)},
		{Name: "Devin_AI",
			WinPaths:   []string{"${APPDATA}\\Devin"},
			MacPaths:   []string{"~/Library/Application Support/Devin"},
			LinuxPaths: []string{"${CONFIG}/Devin"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "OpenHands",
			WinPaths:   []string{"${APPDATA}\\OpenHands"},
			MacPaths:   []string{"~/Library/Application Support/OpenHands"},
			LinuxPaths: []string{"${CONFIG}/OpenHands"},
			Extensions: []string{".json", ".yaml", ".yml", ".env", ".toml"}, MaxFileSize: mb(5)},
		{Name: "Sweep_AI",
			WinPaths:   []string{"${APPDATA}\\Sweep"},
			MacPaths:   []string{"~/Library/Application Support/Sweep"},
			LinuxPaths: []string{"${CONFIG}/Sweep"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Codex_CLI",
			WinPaths:   []string{"${HOME}\\.codex"},
			MacPaths:   []string{"~/.codex"},
			LinuxPaths: []string{"~/.codex"},
			Extensions: []string{".json", ".yaml", ".yml", ".toml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Copilot_Workspace",
			WinPaths:   []string{"${APPDATA}\\GitHub Copilot"},
			MacPaths:   []string{"~/Library/Application Support/GitHub Copilot"},
			LinuxPaths: []string{"${CONFIG}/github-copilot"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Vercel_AI",
			WinPaths:   []string{"${APPDATA}\\Vercel"},
			MacPaths:   []string{"~/Library/Application Support/Vercel"},
			LinuxPaths: []string{"${CONFIG}/vercel"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Bolt_new",
			WinPaths:   []string{"${APPDATA}\\StackBlitz"},
			MacPaths:   []string{"~/Library/Application Support/StackBlitz"},
			LinuxPaths: []string{"${CONFIG}/StackBlitz"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Lovable",
			WinPaths:   []string{"${APPDATA}\\Lovable"},
			MacPaths:   []string{"~/Library/Application Support/Lovable"},
			LinuxPaths: []string{"${CONFIG}/Lovable"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Leonardo_AI",
			WinPaths:   []string{"${APPDATA}\\Leonardo AI"},
			MacPaths:   []string{"~/Library/Application Support/Leonardo AI"},
			LinuxPaths: []string{"${CONFIG}/leonardo-ai"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Ideogram_AI",
			WinPaths:   []string{"${APPDATA}\\Ideogram"},
			MacPaths:   []string{"~/Library/Application Support/Ideogram"},
			LinuxPaths: []string{"${CONFIG}/Ideogram"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Factory_AI",
			WinPaths:   []string{"${HOME}\\.factory"},
			MacPaths:   []string{"~/.factory"},
			LinuxPaths: []string{"~/.factory"},
			Extensions: []string{".json", ".yaml", ".yml", ".env", ".toml"}, MaxFileSize: mb(5)},
		{Name: "CodeSandbox",
			WinPaths:   []string{"${APPDATA}\\CodeSandbox"},
			MacPaths:   []string{"~/Library/Application Support/CodeSandbox"},
			LinuxPaths: []string{"${CONFIG}/CodeSandbox"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "GitPod",
			WinPaths:   []string{"${APPDATA}\\GitPod"},
			MacPaths:   []string{"~/Library/Application Support/GitPod"},
			LinuxPaths: []string{"${CONFIG}/GitPod"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Mintlify",
			WinPaths:   []string{"${APPDATA}\\Mintlify"},
			MacPaths:   []string{"~/Library/Application Support/Mintlify"},
			LinuxPaths: []string{"${CONFIG}/Mintlify"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Augment_Code",
			WinPaths:   []string{"${APPDATA}\\Augment"},
			MacPaths:   []string{"~/Library/Application Support/Augment"},
			LinuxPaths: []string{"${CONFIG}/Augment"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Midjourney",
			WinPaths:   []string{"${APPDATA}\\Midjourney"},
			MacPaths:   []string{"~/Library/Application Support/Midjourney"},
			LinuxPaths: []string{},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "Anthropic_Console",
			WinPaths:   []string{"${APPDATA}\\Anthropic"},
			MacPaths:   []string{"~/Library/Application Support/Anthropic"},
			LinuxPaths: []string{"${CONFIG}/Anthropic"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
		{Name: "OpenAI_Desktop",
			WinPaths:   []string{"${APPDATA}\\OpenAI"},
			MacPaths:   []string{"~/Library/Application Support/OpenAI"},
			LinuxPaths: []string{"${CONFIG}/OpenAI"},
			Extensions: []string{".json", ".yaml", ".yml", ".env"}, MaxFileSize: mb(5)},
	}
}