package scanner

// ================================================================
// 一、GUI 桌面客户端
// ================================================================
func toolsCatGUI() []Tool {
	return []Tool{
		{Name: "Postman",
			WinPaths:   []string{"${APPDATA}\\Postman", "${LOCALAPPDATA}\\Postman"},
			MacPaths:   []string{"~/Library/Application Support/Postman"},
			LinuxPaths: []string{"${CONFIG}/Postman", "~/.config/Postman"},
			Extensions: []string{".json", ".log", ".db"}, MaxFileSize: mb(10)},
		{Name: "Insomnia",
			WinPaths:   []string{"${APPDATA}\\Insomnia"},
			MacPaths:   []string{"~/Library/Application Support/Insomnia"},
			LinuxPaths: []string{"${CONFIG}/Insomnia"},
			Extensions: []string{".json", ".db", ".yml", ".yaml"}, MaxFileSize: mb(10)},
		{Name: "Bruno",
			WinPaths:   []string{"${HOME}\\bruno", "${HOME}\\Documents\\bruno"},
			MacPaths:   []string{"~/bruno", "~/Documents/bruno"},
			LinuxPaths: []string{"~/bruno", "~/Documents/bruno"},
			Extensions: []string{".bru", ".json", ".yml", ".yaml"}, MaxFileSize: mb(5)},
		{Name: "SoapUI",
			WinPaths:   []string{"${HOME}\\SoapUI", "${HOME}\\.soapui", "${USERPROFILE}\\SoapUI"},
			MacPaths:   []string{"~/soapui", "~/.soapui"},
			LinuxPaths: []string{"~/soapui", "~/.soapui"},
			Extensions: []string{".xml", ".properties", ".txt", ".groovy"}, MaxFileSize: mb(20)},
		{Name: "ReadyAPI",
			WinPaths:   []string{"${HOME}\\ReadyAPI", "${HOME}\\.readyapi"},
			MacPaths:   []string{"~/ReadyAPI", "~/.readyapi"},
			LinuxPaths: []string{"~/ReadyAPI", "~/.readyapi"},
			Extensions: []string{".xml", ".properties", ".groovy"}, MaxFileSize: mb(20)},
		{Name: "Apifox",
			WinPaths:   []string{"${APPDATA}\\Apifox", "${LOCALAPPDATA}\\Apifox"},
			MacPaths:   []string{"~/Library/Application Support/Apifox", "~/Library/Caches/Apifox"},
			LinuxPaths: []string{"${CONFIG}/Apifox", "~/.config/Apifox"},
			Extensions: []string{".json", ".db", ".log"}, MaxFileSize: mb(10)},
		{Name: "ApiPost",
			WinPaths:   []string{"${APPDATA}\\ApiPost", "${LOCALAPPDATA}\\ApiPost7"},
			MacPaths:   []string{"~/Library/Application Support/ApiPost"},
			LinuxPaths: []string{"${CONFIG}/ApiPost"},
			Extensions: []string{".json", ".db"}, MaxFileSize: mb(10)},
		{Name: "Postcat",
			WinPaths:   []string{"${APPDATA}\\Postcat", "${APPDATA}\\postcat"},
			MacPaths:   []string{"~/Library/Application Support/Postcat", "~/Library/Application Support/postcat"},
			LinuxPaths: []string{"${CONFIG}/Postcat", "${CONFIG}/postcat"},
			Extensions: []string{".json", ".db", ".yml", ".yaml"}, MaxFileSize: mb(10)},
		{Name: "EoLink",
			WinPaths:   []string{"${APPDATA}\\EoLink", "${LOCALAPPDATA}\\eolink"},
			MacPaths:   []string{"~/Library/Application Support/EoLink"},
			LinuxPaths: []string{"${CONFIG}/EoLink"},
			Extensions: []string{".json", ".db"}, MaxFileSize: mb(10)},
		{Name: "YApi",
			WinPaths:   []string{"${HOME}\\yapi", "${HOME}\\.yapi"},
			MacPaths:   []string{"~/yapi", "~/.yapi"},
			LinuxPaths: []string{"~/yapi", "~/.yapi"},
			Extensions: []string{".json", ".db", ".js", ".conf"}, MaxFileSize: mb(10)},
		{Name: "ShowDoc",
			WinPaths:   []string{"${HOME}\\showdoc"},
			MacPaths:   []string{"~/showdoc"},
			LinuxPaths: []string{"~/showdoc"},
			Extensions: []string{".json", ".php", ".sqlite"}, MaxFileSize: mb(5)},
		{Name: "HTTPie_Desktop",
			WinPaths:   []string{"${APPDATA}\\HTTPie", "${HOME}\\.httpie"},
			MacPaths:   []string{"~/Library/Application Support/HTTPie", "~/.httpie"},
			LinuxPaths: []string{"${CONFIG}/HTTPie", "~/.httpie"},
			Extensions: []string{".json", ".sessions", ".log"}, MaxFileSize: mb(5)},
		{Name: "Hoppscotch_Desktop",
			WinPaths:   []string{"${APPDATA}\\hoppscotch", "${LOCALAPPDATA}\\hoppscotch"},
			MacPaths:   []string{"~/Library/Application Support/hoppscotch"},
			LinuxPaths: []string{"${CONFIG}/hoppscotch"},
			Extensions: []string{".json", ".db"}, MaxFileSize: mb(5)},
		{Name: "SwaggerHub_Desktop",
			WinPaths:   []string{"${APPDATA}\\SwaggerHub", "${APPDATA}\\swaggerhub"},
			MacPaths:   []string{"~/Library/Application Support/SwaggerHub"},
			LinuxPaths: []string{"${CONFIG}/SwaggerHub", "${CONFIG}/swaggerhub"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "Stoplight_Studio",
			WinPaths:   []string{"${APPDATA}\\Stoplight Studio", "${APPDATA}\\stoplight-studio"},
			MacPaths:   []string{"~/Library/Application Support/Stoplight Studio"},
			LinuxPaths: []string{"${CONFIG}/Stoplight Studio", "${CONFIG}/stoplight-studio"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "ReadMe_CLI",
			WinPaths:   []string{"${HOME}\\.readme", "${HOME}\\.rdme"},
			MacPaths:   []string{"~/.readme", "~/.rdme"},
			LinuxPaths: []string{"~/.readme", "~/.rdme"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(1)},
		{Name: "Redocly_CLI",
			WinPaths:   []string{"${HOME}\\.redocly", "${HOME}\\.redocly.yaml", "${HOME}\\.redocly.yml"},
			MacPaths:   []string{"~/.redocly", "~/.redocly.yaml", "~/.redocly.yml"},
			LinuxPaths: []string{"~/.redocly", "~/.redocly.yaml", "~/.redocly.yml"},
			Extensions: []string{".yaml", ".yml", ".json"}, MaxFileSize: mb(1)},

		// ================================================================
		// 二、gRPC / GraphQL / MQTT / WebSocket 客户端
		// ================================================================
		{Name: "BloomRPC",
			WinPaths:   []string{"${APPDATA}\\bloomrpc", "${APPDATA}\\BloomRPC"},
			MacPaths:   []string{"~/Library/Application Support/bloomrpc", "~/Library/Application Support/BloomRPC"},
			LinuxPaths: []string{"${CONFIG}/bloomrpc", "${CONFIG}/BloomRPC"},
			Extensions: []string{".json"}, MaxFileSize: mb(5)},
		{Name: "gRPC_UI",
			WinPaths:   []string{"${APPDATA}\\grpcui"},
			MacPaths:   []string{"~/Library/Application Support/grpcui"},
			LinuxPaths: []string{"${CONFIG}/grpcui"},
			Extensions: []string{".json"}, MaxFileSize: mb(5)},
		{Name: "Altair_GraphQL",
			WinPaths:   []string{"${APPDATA}\\Altair", "${APPDATA}\\altair"},
			MacPaths:   []string{"~/Library/Application Support/Altair", "~/Library/Application Support/altair"},
			LinuxPaths: []string{"${CONFIG}/Altair", "${CONFIG}/altair"},
			Extensions: []string{".json", ".graphql", ".db"}, MaxFileSize: mb(10)},
		{Name: "GraphQL_Playground",
			WinPaths:   []string{"${APPDATA}\\GraphQL Playground", "${APPDATA}\\graphql-playground"},
			MacPaths:   []string{"~/Library/Application Support/GraphQL Playground"},
			LinuxPaths: []string{"${CONFIG}/GraphQL Playground", "${CONFIG}/graphql-playground"},
			Extensions: []string{".json", ".graphql"}, MaxFileSize: mb(5)},
		{Name: "GraphiQL",
			WinPaths:   []string{"${APPDATA}\\GraphiQL"},
			MacPaths:   []string{"~/Library/Application Support/GraphiQL"},
			LinuxPaths: []string{"${CONFIG}/GraphiQL"},
			Extensions: []string{".json"}, MaxFileSize: mb(5)},
		{Name: "MQTT_Explorer",
			WinPaths:   []string{"${APPDATA}\\MQTT-Explorer", "${APPDATA}\\mqtt-explorer"},
			MacPaths:   []string{"~/Library/Application Support/MQTT-Explorer"},
			LinuxPaths: []string{"${CONFIG}/MQTT-Explorer", "${CONFIG}/mqtt-explorer"},
			Extensions: []string{".json", ".db"}, MaxFileSize: mb(5)},
		{Name: "MQTTX",
			WinPaths:   []string{"${APPDATA}\\MQTTX", "${APPDATA}\\mqttx"},
			MacPaths:   []string{"~/Library/Application Support/MQTTX"},
			LinuxPaths: []string{"${CONFIG}/MQTTX", "${CONFIG}/mqttx"},
			Extensions: []string{".json", ".db"}, MaxFileSize: mb(5)},
	}
}