package scanner

// ================================================================
// 五、CLI 命令行工具
// ================================================================
func toolsCatCLI() []Tool {
	return []Tool{
		{Name: "cURL",
			WinPaths:   []string{"${HOME}\\.curlrc", "${HOME}\\_curlrc"},
			MacPaths:   []string{"~/.curlrc"},
			LinuxPaths: []string{"~/.curlrc"},
			MaxFileSize: mb(1)},
		{Name: "HTTPie_CLI",
			WinPaths:   []string{"${HOME}\\.httpie"},
			MacPaths:   []string{"~/.httpie"},
			LinuxPaths: []string{"~/.httpie"},
			Extensions: []string{".json"}, MaxFileSize: mb(5)},
		{Name: "HTTP_Prompt",
			WinPaths:   []string{"${HOME}\\.http-prompt", "${HOME}\\.http_prompt"},
			MacPaths:   []string{"~/.http-prompt", "~/.http_prompt"},
			LinuxPaths: []string{"~/.http-prompt", "~/.http_prompt"},
			Extensions: []string{".json", ".py"}, MaxFileSize: mb(1)},
		{Name: "xh",
			WinPaths:   []string{"${HOME}\\.config\\xh"},
			MacPaths:   []string{"~/.config/xh"},
			LinuxPaths: []string{"~/.config/xh", "${CONFIG}/xh"},
			Extensions: []string{".json", ".toml"}, MaxFileSize: mb(1)},
		{Name: "Newman",
			WinPaths:   []string{"${HOME}\\.newman", "${HOME}\\newman"},
			MacPaths:   []string{"~/.newman", "~/newman"},
			LinuxPaths: []string{"~/.newman", "~/newman"},
			Extensions: []string{".json", ".js"}, MaxFileSize: mb(5)},
		{Name: "StepCI",
			WinPaths:   []string{"${HOME}\\.stepci", "${HOME}\\stepci"},
			MacPaths:   []string{"~/.stepci", "~/stepci"},
			LinuxPaths: []string{"~/.stepci", "~/stepci"},
			Extensions: []string{".yaml", ".yml", ".json", ".js"}, MaxFileSize: mb(5)},
		{Name: "Dredd",
			WinPaths:   []string{"${HOME}\\.dreddrc", "${HOME}\\dredd.yml"},
			MacPaths:   []string{"~/.dreddrc", "~/dredd.yml"},
			LinuxPaths: []string{"~/.dreddrc", "~/dredd.yml"},
			Extensions: []string{".yml", ".yaml", ".json"}, MaxFileSize: mb(2)},
		{Name: "Hurl",
			WinPaths:   []string{"${HOME}\\.hurl"},
			MacPaths:   []string{"~/.hurl"},
			LinuxPaths: []string{"~/.hurl"},
			Extensions: []string{".hurl"}, MaxFileSize: mb(5)},
		{Name: "vegeta",
			WinPaths:   []string{"${HOME}\\vegeta"},
			MacPaths:   []string{"~/vegeta"},
			LinuxPaths: []string{"~/vegeta"},
			Extensions: []string{".json", ".bin"}, MaxFileSize: mb(20)},
		{Name: "hey",
			WinPaths:   []string{"${HOME}\\hey"},
			MacPaths:   []string{"~/hey"},
			LinuxPaths: []string{"~/hey"},
			Extensions: []string{".csv", ".json"}, MaxFileSize: mb(10)},
		{Name: "wrk",
			WinPaths:   []string{"${HOME}\\.wrk", "${HOME}\\wrk"},
			MacPaths:   []string{"~/.wrk", "~/wrk"},
			LinuxPaths: []string{"~/.wrk", "~/wrk"},
			Extensions: []string{".lua", ".json"}, MaxFileSize: mb(5)},
		{Name: "Siege",
			WinPaths:   []string{"${HOME}\\.siegerc", "${HOME}\\.siege"},
			MacPaths:   []string{"~/.siegerc", "~/.siege"},
			LinuxPaths: []string{"~/.siegerc", "~/.siege"},
			MaxFileSize: mb(1)},
		{Name: "Apache_Bench",
			WinPaths:   []string{"${HOME}\\ab", "${HOME}\\ApacheBench"},
			MacPaths:   []string{"~/ab", "~/ApacheBench"},
			LinuxPaths: []string{"~/ab", "~/ApacheBench"},
			MaxFileSize: mb(5)},
		{Name: "Artillery",
			WinPaths:   []string{"${HOME}\\artillery", "${HOME}\\.artillery"},
			MacPaths:   []string{"~/artillery", "~/.artillery"},
			LinuxPaths: []string{"~/artillery", "~/.artillery"},
			Extensions: []string{".yaml", ".yml", ".json", ".js"}, MaxFileSize: mb(10)},
		{Name: "Gatling",
			WinPaths:   []string{"${HOME}\\gatling", "${HOME}\\.gatling"},
			MacPaths:   []string{"~/gatling", "~/.gatling"},
			LinuxPaths: []string{"~/gatling", "~/.gatling"},
			Extensions: []string{".scala", ".conf", ".properties"}, MaxFileSize: mb(10)},
		{Name: "Locust",
			WinPaths:   []string{"${HOME}\\locust", "${HOME}\\.locust"},
			MacPaths:   []string{"~/locust", "~/.locust"},
			LinuxPaths: []string{"~/locust", "~/.locust"},
			Extensions: []string{".py", ".conf", ".json"}, MaxFileSize: mb(5)},
		{Name: "Ddosify",
			WinPaths:   []string{"${HOME}\\.ddosify", "${HOME}\\ddosify"},
			MacPaths:   []string{"~/.ddosify", "~/ddosify"},
			LinuxPaths: []string{"~/.ddosify", "~/ddosify"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(5)},
		{Name: "go_hit",
			WinPaths:   []string{"${HOME}\\go-hit", "${HOME}\\.go-hit"},
			MacPaths:   []string{"~/go-hit", "~/.go-hit"},
			LinuxPaths: []string{"~/go-hit", "~/.go-hit"},
			Extensions: []string{".yaml", ".yml", ".json"}, MaxFileSize: mb(5)},
		{Name: "gRPCurl_CLI",
			WinPaths:   []string{"${HOME}\\.grpcurl", "${HOME}\\.config\\grpcurl"},
			MacPaths:   []string{"~/.grpcurl", "~/.config/grpcurl"},
			LinuxPaths: []string{"~/.grpcurl", "~/.config/grpcurl"},
			Extensions: []string{".json", ".yaml"}, MaxFileSize: mb(1)},
		{Name: "Evans",
			WinPaths:   []string{"${HOME}\\.evans", "${HOME}\\.evans.toml"},
			MacPaths:   []string{"~/.evans", "~/.evans.toml"},
			LinuxPaths: []string{"~/.evans", "~/.evans.toml"},
			Extensions: []string{".toml", ".yaml"}, MaxFileSize: mb(1)},

		// ================================================================
		// 六、Mock / 代理工具
		// ================================================================
		{Name: "Charles_Proxy",
			WinPaths:   []string{"${APPDATA}\\Charles"},
			MacPaths:   []string{"~/Library/Application Support/Charles"},
			LinuxPaths: []string{"~/.charles"},
			Extensions: []string{".xml", ".json", ".chls"}, MaxFileSize: mb(50)},
		{Name: "Fiddler",
			WinPaths:   []string{"${LOCALAPPDATA}\\Fiddler", "${HOME}\\Documents\\Fiddler2"},
			MacPaths:   []string{"~/Fiddler", "~/.fiddler"},
			LinuxPaths: []string{"~/Fiddler", "~/.fiddler"},
			Extensions: []string{".xml", ".saz", ".json", ".txt"}, MaxFileSize: mb(50)},
		{Name: "Proxyman",
			WinPaths:   []string{"${APPDATA}\\Proxyman", "${LOCALAPPDATA}\\Proxyman"},
			MacPaths:   []string{"~/Library/Application Support/Proxyman", "~/Library/Caches/Proxyman"},
			LinuxPaths: []string{"~/.config/proxyman", "~/.proxyman"},
			Extensions: []string{".json", ".log", ".db"}, MaxFileSize: mb(50)},
		{Name: "mitmproxy",
			WinPaths:   []string{"${HOME}\\.mitmproxy"},
			MacPaths:   []string{"~/.mitmproxy"},
			LinuxPaths: []string{"~/.mitmproxy"},
			Extensions: []string{".yaml", ".yml", ".json", ".flow"}, MaxFileSize: mb(100)},
		{Name: "WireMock",
			WinPaths:   []string{"${HOME}\\wiremock", "${HOME}\\.wiremock"},
			MacPaths:   []string{"~/wiremock", "~/.wiremock"},
			LinuxPaths: []string{"~/wiremock", "~/.wiremock"},
			Extensions: []string{".json", ".java", ".properties"}, MaxFileSize: mb(10)},
		{Name: "MockServer",
			WinPaths:   []string{"${HOME}\\mockserver", "${HOME}\\.mockserver"},
			MacPaths:   []string{"~/mockserver", "~/.mockserver"},
			LinuxPaths: []string{"~/mockserver", "~/.mockserver"},
			Extensions: []string{".json", ".java", ".properties"}, MaxFileSize: mb(10)},
		{Name: "Mountebank",
			WinPaths:   []string{"${HOME}\\mountebank", "${HOME}\\.mb"},
			MacPaths:   []string{"~/mountebank", "~/.mb"},
			LinuxPaths: []string{"~/mountebank", "~/.mb"},
			Extensions: []string{".json", ".ejs", ".js"}, MaxFileSize: mb(5)},
		{Name: "JSON_Server",
			WinPaths:   []string{"${HOME}\\json-server", "${HOME}\\.json-server"},
			MacPaths:   []string{"~/json-server", "~/.json-server"},
			LinuxPaths: []string{"~/json-server", "~/.json-server"},
			Extensions: []string{".json", ".js"}, MaxFileSize: mb(5)},
		{Name: "Prism",
			WinPaths:   []string{"${HOME}\\.prism", "${HOME}\\.prismrc"},
			MacPaths:   []string{"~/.prism", "~/.prismrc"},
			LinuxPaths: []string{"~/.prism", "~/.prismrc"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(2)},
		{Name: "Hoverfly",
			WinPaths:   []string{"${HOME}\\.hoverfly", "${HOME}\\hoverfly"},
			MacPaths:   []string{"~/.hoverfly", "~/hoverfly"},
			LinuxPaths: []string{"~/.hoverfly", "~/hoverfly"},
			Extensions: []string{".json", ".yaml", ".yml"}, MaxFileSize: mb(10)},

		// ================================================================
		// 七、安全测试工具
		// ================================================================
		{Name: "OWASP_ZAP",
			WinPaths:   []string{"${HOME}\\OWASP ZAP", "${HOME}\\.ZAP", "${HOME}\\ZAP"},
			MacPaths:   []string{"~/OWASP ZAP", "~/.ZAP", "~/ZAP"},
			LinuxPaths: []string{"~/OWASP_ZAP", "~/.ZAP", "~/ZAP"},
			Extensions: []string{".xml", ".session", ".properties", ".json"}, MaxFileSize: mb(20)},
		{Name: "Burp_Suite",
			WinPaths:   []string{"${HOME}\\BurpSuite", "${HOME}\\.BurpSuite", "${APPDATA}\\BurpSuite"},
			MacPaths:   []string{"~/BurpSuite", "~/.BurpSuite"},
			LinuxPaths: []string{"~/BurpSuite", "~/.BurpSuite"},
			Extensions: []string{".xml", ".json", ".properties", ".burp"}, MaxFileSize: mb(50)},
		{Name: "Sqlmap",
			WinPaths:   []string{"${HOME}\\.sqlmap", "${HOME}\\sqlmap"},
			MacPaths:   []string{"~/.sqlmap", "~/sqlmap"},
			LinuxPaths: []string{"~/.sqlmap", "~/sqlmap"},
			Extensions: []string{".conf", ".csv", ".xml"}, MaxFileSize: mb(5)},

		// ================================================================
		// 八、性能测试工具（商业/企业级）
		// ================================================================
		{Name: "LoadRunner",
			WinPaths:   []string{"${HOME}\\LoadRunner", "${PROGRAMFILES}\\HP\\LoadRunner", "${PROGRAMFILES(x86)}\\HP\\LoadRunner"},
			MacPaths:   []string{"~/LoadRunner", "/Applications/HP/LoadRunner"},
			LinuxPaths: []string{"~/LoadRunner", "/opt/HP/LoadRunner"},
			Extensions: []string{".usr", ".lrs", ".cfg", ".dat"}, MaxFileSize: mb(50)},
		{Name: "NeoLoad",
			WinPaths:   []string{"${HOME}\\NeoLoad", "${HOME}\\.neoload"},
			MacPaths:   []string{"~/NeoLoad", "~/.neoload"},
			LinuxPaths: []string{"~/NeoLoad", "~/.neoload"},
			Extensions: []string{".nlp", ".xml", ".properties", ".json"}, MaxFileSize: mb(50)},
	}
}